name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Enable Corepack (Yarn)
      run: corepack enable
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Cache Node modules
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install dependencies
      working-directory: ./frontend
      run: yarn install --frozen-lockfile
      
    - name: Build Web App
      working-directory: ./frontend
      run: yarn build
      env:
        DISABLE_ESLINT_PLUGIN: true
        GENERATE_SOURCEMAP: false
        REACT_APP_BACKEND_URL: ${{ secrets.BACKEND_URL || 'https://pizoomatch.preview.emergentagent.com' }}
        
    - name: Sync Capacitor
      working-directory: ./frontend
      run: npx cap sync android
      
    - name: Build Android Debug APK
      working-directory: ./frontend/android
      run: ./gradlew assembleDebug --no-daemon
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pizoo-debug-apk
        path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
